pipeline {
    agent any

    tools {
        maven 'maven'
    }
    
    stages {
        stage('build') {
            steps {
               echo "compiling the application" 
               dir('worker') {
               sh 'mvn compile'
               }
            }
        }
         stage('test') {
            steps {
                echo "Running unit tests for worker app" 
                 dir('worker') {
                   sh 'mvn clean test'
               }
                
            }
        }
         stage('package') {
            when {
            branch 'master'
            changeset "**/worker/**"
        }
            steps {
                echo "Packing the worker App" 
                 dir('worker') {
                  sh 'mvn package -DskipTests'
                   archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
               }
            }
        }
    }
    
    post {
        
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo "Build pipeline is complete"
        }
    }
}