pipeline {
    agent any

    tools {
        maven 'maven 3.9.3'
    }
    
    stages {
        stage('build') {
            steps {
               echo "compiling the application" 
               dir('worker') {
               sh 'mvn compile'
               }
            }
        }
         stage('test') {
            steps {
                echo "Running unit tests for worker app" 
                 dir('worker') {
                   sh 'mvn clean test'
               }
                
            }
        }
         stage('package') {
            steps {
                echo "Packing the worker App" 
                 dir('worker') {
                  sh 'mvn package'
               }
            }
        }
    }
    
    post {
        always {
            echo "Build pipeline is complete"
        }
    }
}